(define (problem snow_p3)
    (:domain snow)
    (:objects d1 d2 d3 w1 w2 w3 - LocationType)
    (:init
        (atDry)
        (drySnow d1)
        (drySnow d2)
        (drySnow d3)
        (wetSnow w1)
        (wetSnow w2)
        (wetSnow w3)
        (not (dryCleared d1))
        (not (dryCleared d2))
        (not (dryCleared d3))
        (not (wetCleared w1))
        (not (wetCleared w2))
        (not (wetCleared w3))
    )
    (:goal
        (and (atDry) (dryCleared d1) (dryCleared d2) (dryCleared d3) (wetCleared w1) (wetCleared w2) (wetCleared w3))
    )
)
