(define (domain snow)
    (:requirements :strips :typing :equality :derived-predicates :negative-preconditions :universal-preconditions)
    (:types LocationType)
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (:predicates
        (atDry)
        (atWet)
        (drySnow ?l - LocationType)
        (wetSnow ?l - LocationType)
        (dryCleared ?l - LocationType)
        (wetCleared ?l - LocationType)
        (vStart)
        (Vgoal)
        (allDryCleared)
        (allWetCleared)
        (allCleared)
    )
    (:derived (allDryCleared)
        (forall (?l - LocationType) (dryCleared ?l))
    )
    (:derived (allWetCleared)
        (forall (?l - LocationType) (wetCleared ?l))
    )
    (:derived (allCleared)
        (and (allDryCleared) (allWetCleared))
    )
    ;; ##### ACTIONS #####
    (:action shovelDry
        :parameters (?l - LocationType)
        :precondition (and (atDry) (drySnow ?l) (not (dryCleared ?l)))
        :effect (and (dryCleared ?l) (not (drySnow ?l)))
    )
    (:action shovelWet
        :parameters (?l - LocationType)
        :precondition (and (atWet) (wetSnow ?l) (not (wetCleared ?l)))
        :effect (and (wetCleared ?l) (not (wetSnow ?l)))
    )
    (:action moveDry
        :parameters ()
        :precondition (atWet)
        :effect (and (atDry) (not (atWet)))
    )
    (:action moveWet
        :parameters ()
        :precondition (atDry)
        :effect (and (atWet) (not (atDry)))
    )
    (:formula_for_initial_states (and (atDry) (exists (?l - LocationType) (drySnow ?l))))
    (:formula_for_goals (and (atDry) (allCleared)))
)
