(define (problem RGBBlocks_p4) 
    (:domain RGBBlocks)
    (:objects
        i1 i2 i3 i4 - BlockType)
    (:init
        (on_table Bottom)
        (on i1 Bottom)
        (on i2 i1)
        (on i3 i2)
        (on i4 i3)
        (clear i4)
        (isRed i1)
        (isBlue i2)
        (isGreen i3)
        (isRed i4)
        (arm_empty)
    )
    (:goal (and
        (clear Bottom)
        (inRedBox i1)
        (inBlueBox i2)
        (inGreenBox i3)
        (inRedBox i4)
        ))
)
