#!/bin/bash
DOMAIN_NAME=${1}
echo ">>> Solving FOND problem for domain: ${DOMAIN_NAME}" >&2
mkdir -p ./solutionsByPRP
./prp/prp ./autogenerated/fond_${DOMAIN_NAME}_d.pddl ./autogenerated/fond_${DOMAIN_NAME}_p.pddl --dump-policy 2 --optimize-final-policy 1

# translate_policy.py is a small regex-only script; runs on python3 too.
python ./prp-scripts/translate_policy.py > ./solutionsByPRP/fond_${DOMAIN_NAME}_human_policy.out

# Also archive the raw PRP policy output for inspection.
if [ -f policy.out ]; then
    cp policy.out ./solutionsByPRP/fond_${DOMAIN_NAME}_policy.out
fi