(define (domain treechop)
    (:requirements :strips :typing :equality :derived-predicates :negative-preconditions :universal-preconditions)
    (:types BranchType)
    (:constants Trunk - BranchType)
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (:predicates
        (onTree ?b - BranchType)
        (chopped ?b - BranchType)
        (clear ?b - BranchType)
        (treeDown)
        (arm_empty)
        (holding ?b - BranchType)
        (vStart)
        (VGoal)
        (allBranchesChopped)
        (H)
    )
    (:derived (allBranchesChopped)
        (forall (?b - BranchType) (or (chopped ?b) (== ?b Trunk)))
    )
    (:derived (H)
        (exists (?b - BranchType) (holding ?b))
    )
    (:derived (vGoal)
        (treeDown)
    )
    ;; ##### ACTIONS #####
    (:action chopBranch
        :parameters (?b - BranchType)
        :precondition (and (onTree ?b) (clear ?b) (arm_empty))
        :effect (and (holding ?b) (not (arm_empty)))
    )
    (:action dropBranch
        :parameters (?b - BranchType)
        :precondition (holding ?b)
        :effect (and (chopped ?b) (arm_empty) (not (holding ?b)))
    )
    (:action fellTree
        :parameters ()
        :precondition (and (allBranchesChopped) (arm_empty) (not (treeDown)))
        :effect (treeDown)
    )
    (:formula_for_initial_states (and (arm_empty) (not (treeDown)) (forall (?b - BranchType) (or (onTree ?b) (== ?b Trunk)))))
    (:formula_for_goals (and (treeDown)))
)
