(define (problem treechop_p3)
    (:domain treechop)
    (:objects b1 b2 b3 - BranchType)
    (:init
        (onTree b1)
        (onTree b2)
        (onTree b3)
        (clear b1)
        (clear b2)
        (clear b3)
        (arm_empty)
        (not (treeDown))
    )
    (:goal (and (treeDown)))
)
