(define (problem 3delivery_p3)
    (:domain 3delivery)
    (:objects p1 p2 p3 - PackageType)
    (:init
        (atDepotPkg p1)
        (atDepotPkg p2)
        (atDepotPkg p3)
        (arm_empty)
        (not (inTruck p1))
        (not (inTruck p2))
        (not (inTruck p3))
        (not (delivered p1))
        (not (delivered p2))
        (not (delivered p3))
    )
    (:goal (and (delivered p1) (delivered p2) (delivered p3)))
)
