(define (problem 3delivery_p2)
    (:domain 3delivery)
    (:objects p1 p2 - PackageType)
    (:init
        (atDepotPkg p1)
        (atDepotPkg p2)
        (arm_empty)
        (not (inTruck p1))
        (not (inTruck p2))
        (not (delivered p1))
        (not (delivered p2))
    )
    (:goal (and (delivered p1) (delivered p2)))
)
