(define (problem choppingtree2_p3)
    (:domain choppingtree2)
    (:objects b1 b2 b3 - BranchType)
    (:init
        (onTree b1)
        (onTree b2)
        (onTree b3)
        (clear b1)
        (clear b2)
        (clear b3)
        (arm_empty)
    )
    (:goal (and (chopped b1) (chopped b2) (chopped b3)))
)
