(define (domain nestedvar)
    (:requirements :strips :typing :equality :derived-predicates :negative-preconditions)
    (:types ItemType)
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (:predicates
        (inX1 ?i - ItemType)
        (inX2 ?i - ItemType)
        (vStart)
        (Vgoal)
        (x2empty)
        (h_x1empty)
        (h_hasX2)
    )
    (:derived (h_x1empty)
        (not (exists (?i - ItemType) (inX1 ?i)))
    )
    (:derived (h_hasX2)
        (exists (?i - ItemType) (inX2 ?i))
    )
    (:derived (vGoal)
        (and (h_x1empty) (not(h_hasX2)))
    )
    ;; ##### ACTIONS #####
    (:action decX1
        :parameters (?i - ItemType)
        :precondition (and (inX1 ?i) (x2empty))
        :effect (and (inX2 ?i) (not (inX1 ?i)) (not (x2empty)))
    )
    (:action decX2
        :parameters (?i - ItemType)
        :precondition (inX2 ?i)
        :effect (and (not (inX2 ?i)) (x2empty))
    )
    (:formula_for_initial_states (and (x2empty) (exists (?i - ItemType) (inX1 ?i))))
    (:formula_for_goals (and (h_x1empty) (x2empty)))
)
