(define (domain trashcollection)
    (:requirements :strips :typing :equality :derived-predicates :negative-preconditions :universal-preconditions)
    (:types LocationType TrashType)
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (:predicates
        (trashAt ?l - LocationType ?t - TrashType)
        (inTruck ?t - TrashType)
        (atDump)
        (atLoc ?l - LocationType)
        (truckEmpty)
        (vStart)
        (Vgoal)
        (allCollected)
        (h_carrying)
    )
    (:derived (allCollected)
        (not (exists (?l - LocationType) (exists (?t - TrashType) (trashAt ?l ?t))))
    )
    (:derived (h_carrying)
        (exists (?t - TrashType) (inTruck ?t))
    )
    ;; ##### ACTIONS #####
    (:action collectTrash
        :parameters (?l - LocationType ?t - TrashType)
        :precondition (and (atLoc ?l) (trashAt ?l ?t) (truckEmpty))
        :effect (and (inTruck ?t) (not (trashAt ?l ?t)) (not (truckEmpty)))
    )
    (:action depositTrash
        :parameters (?t - TrashType)
        :precondition (and (atDump) (inTruck ?t))
        :effect (and (not (inTruck ?t)) (truckEmpty))
    )
    (:action moveToLoc
        :parameters (?l - LocationType)
        :precondition (and (atDump) (not (atLoc ?l)))
        :effect (and (atLoc ?l) (not (atDump)))
    )
    (:action moveToDump
        :parameters (?l - LocationType)
        :precondition (and (atLoc ?l) (not (atDump)))
        :effect (and (atDump) (not (atLoc ?l)))
    )
    (:formula_for_initial_states (and (atDump) (truckEmpty) (exists (?l - LocationType) (exists (?t - TrashType) (trashAt ?l ?t)))))
    (:formula_for_goals (and (atDump) (allCollected)))
)
