# -*- coding: UTF-8 -*-
#!/usr/bin/env python
#-------------------------------------------------------------------------------
# Name:        Automatic verification of $m(hs_\{pre\}) \impolies Poss(a_k)$ for FOND Abstraction.
# Author:      this file is autogenerated by "PossVerification.py/autogenerator_python_prove_file()"
# Created:     Wed Jul 15 00:17:45 2026
# Copyright:   (c) Tridu33 2022
# Licence:     <MIT licence>
#-------------------------------------------------------------------------------
from z3 import *
from func_timeout import func_set_timeout
import func_timeout,time,os


PackageType = DeclareSort("PackageType")
p = Const('p', PackageType)
v0 = Const('v0', PackageType)
v1 = Const('v1', PackageType)

# declare Predicates 
atDepotPkg = Function('atDepotPkg',PackageType,BoolSort())
inTruck = Function('inTruck',PackageType,BoolSort())
delivered = Function('delivered',PackageType,BoolSort())
arm_empty = Bool('arm_empty')
vStart = Bool('vStart')
Vgoal = Bool('Vgoal')
allDelivered = Bool('allDelivered')
h_carrying = Bool('h_carrying')

# load and exec domain constraint file of "3delivery" given by users(background information).
grader_father_src_path = os.path.abspath(os.path.dirname(__file__)+os.path.sep+"..")
for line in open('./constrainsConfig/3delivery_constrain.txt','r'): 
    exec(line)
@func_set_timeout(1000)
def myprove(f):
    s = Solver()
    s.add(Not(f))
    # print(s.sexpr())
    if s.check() == unsat:
        del s
        print(os.path.basename(__file__)[:-3]+" is proved.")
    else:
        print(os.path.basename(__file__)[:-3]+" failed to prove")
############################### start to prove! ####################################
hig = Or(And(Not(ForAll([p],(delivered(p)))),Not(Exists([p],(inTruck(p)))) ))
low = And(arm_empty,Not(Exists([p],(inTruck(p)))),Not(ForAll([p],(delivered(p)))),Exists([p],(atDepotPkg(p))))
goal = And(
    Implies(
        And(constraint,simplify(low)),
        hig
    )
)
try:
    # print(simplify(goal))
    myprove(goal)
except func_timeout.exceptions.FunctionTimedOut:
    print('timeout and unknown,please open \''+os.path.basename(__file__)+'\' and try.')
