# -*- coding: UTF-8 -*-
#!/usr/bin/env python
#-------------------------------------------------------------------------------
# Name:        Automatic verification of $m(hs_\{pre\}) \impolies Poss(a_k)$ for FOND Abstraction.
# Author:      this file is autogenerated by "PossVerification.py/autogenerator_python_prove_file()"
# Created:     Wed Jul 15 22:38:51 2026
# Copyright:   (c) Tridu33 2022
# Licence:     <MIT licence>
#-------------------------------------------------------------------------------
from z3 import *
from func_timeout import func_set_timeout
import func_timeout,time,os



# declare Predicates 
zero5L = Bool('zero5L')
one5L = Bool('one5L')
two5L = Bool('two5L')
three5L = Bool('three5L')
four5L = Bool('four5L')
five5L = Bool('five5L')
zero3L = Bool('zero3L')
one3L = Bool('one3L')
two3L = Bool('two3L')
three3L = Bool('three3L')
vStart = Bool('vStart')
vGoal = Bool('vGoal')

# load and exec domain constraint file of "bottle4L" given by users(background information).
grader_father_src_path = os.path.abspath(os.path.dirname(__file__)+os.path.sep+"..")
for line in open('./constrainsConfig/bottle4L_constrain.txt','r'): 
    exec(line)
@func_set_timeout(1000)
def myprove(f):
    s = Solver()
    s.add(Not(f))
    # print(s.sexpr())
    if s.check() == unsat:
        del s
        print(os.path.basename(__file__)[:-3]+" is proved.")
    else:
        print(os.path.basename(__file__)[:-3]+" failed to prove")
############################### start to prove! ####################################
hig = Or(And( ))
low = And(zero5L,zero3L,vStart)
goal = And(
    Implies(
        And(constraint,simplify(low)),
        hig
    )
)
try:
    # print(simplify(goal))
    myprove(goal)
except func_timeout.exceptions.FunctionTimedOut:
    print('timeout and unknown,please open \''+os.path.basename(__file__)+'\' and try.')
