
import sys, pprint,os,json,time, copy,re,argparse
from PDDLParser import PDDLParser 
from Simulator import Simulator
from HigState import HigState
from LowState import LowState
from constants import DEBUG
from utils import *
from FondDomainAndOrGraph import FondDomainAndOrGraph
import pickle

filename = "autogenerated/{0}.bitefile".format("striped")
# Open the target file in binary read mode
f = open(filename, 'rb')
#  Loads variables from the file into the current workspace
cur_sub_fond_graph = pickle.load(f)
print(cur_sub_fond_graph)