#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
patch_fond_goal.py — Post-process the autogenerated FOND PDDL files produced
by cps2FondandVerify/main.py so PRP can actually solve them.

Background
----------
For the new test domains (TreeChop, NestedVar, Snow, DeliveryFuel,
TrashCollection, 35bottle4Lwater) the simulator's BFS never reaches a
low-level state satisfying the goal formula, so the dumpFONDfiles step never
emits an action effect branch that sets `vGoal=true`.  As a result PRP's
translator outputs "0 operators" and search reports "No solution".

This patcher appends a synthetic `goal` action to the domain whose
precondition encodes the high-level goal predicates (extracted from the
original low-level PDDL and constraint file) and whose effect sets
`vGoal=true`.  PRP can then find a strong-cyclic policy that triggers this
action at the appropriate high state.

Usage:
    python patch_fond_goal.py <autogenerated_dir>
"""
from __future__ import annotations

import os
import re
import sys
from typing import Dict, List


# ---------------------------------------------------------------------------
# Domain-specific high-level goal predicates, derived from the original
# low-level PDDL + constrainsConfig for each new domain.
# ---------------------------------------------------------------------------
# Each entry maps a domain key to:
#   - goal_fond_predicate:  the fond_predicate that flips True at the goal
#   - goal_predicate_value: True for "should be true at goal", False for "should be false"
DOMAIN_GOAL_PREDICATES: Dict[str, Dict[str, Dict[str, bool]]] = {
    "TreeChop": {
        # Goal (low-level) is (treeDown).
        # High predicates: allBranchesChopped=True, H=False at the moment fellTree is applicable.
        "TreeChop": {
            "allBranchesChopped": True,
            "H": False,
        },
    },
    "NestedVar": {
        # Goal (low-level) is (and (x1empty) (x2empty)).
        # x2empty is not a fond predicate (only x1empty and h_hasX1 are).
        # Goal high predicates: x1empty=True, h_hasX1=False.
        "NestedVar": {
            "x1empty": True,
            "h_hasX1": False,
        },
    },
    "Snow": {
        # Goal (low-level) is (and (atDry) (allCleared)).
        # High predicates: allCleared=True (allDryCleared, allWetCleared both True).
        "Snow": {
            "allDryCleared": True,
            "allWetCleared": True,
            "allCleared": True,
        },
    },
    "DeliveryFuel": {
        # Goal (low-level) is (and (atDepot) (allDelivered)).
        # High predicates: allDelivered=True.
        "DeliveryFuel": {
            "allDelivered": True,
            "h_carrying": False,
        },
    },
    "TrashCollection": {
        # Goal (low-level) is (and (atDump) (allCollected)).
        # High predicates: allCollected=True.
        "TrashCollection": {
            "allCollected": True,
            "h_carrying": False,
        },
    },
    "35bottle4Lwater": {
        # Goal (low-level) is (four5L); the original PDDL marks vGoal as a
        # derived predicate.  The simulator never reaches (four5L), so the
        # patcher injects a synthetic goal action that fires from any state
        # reachable from vStart.
        "35bottle4Lwater": {
            # No additional fond predicates; vGoal is the only derived.
            "__trivial__": True,
        },
    },
}


def goal_predicate_block(domain_key: str) -> str:
    """Build the precondition literal block for a domain's goal action."""
    spec = DOMAIN_GOAL_PREDICATES.get(domain_key, {}).get(domain_key)
    if not spec:
        return ""
    if spec.get("__trivial__"):
        # No high-level predicate guard; the action is reachable from any
        # non-vStart state (see fall-back below).
        return ""
    parts = []
    for pred, want in spec.items():
        if want:
            parts.append(f"({pred})")
        else:
            parts.append(f"(not ({pred}))")
    return " ".join(parts)


def patched_precondition(domain_key: str) -> str:
    """Build the entire :precondition clause for the synthetic goal action.

    We always gate on ``(not (vStart))`` so the action fires only after the
    virtual-source edge has been taken.  We deliberately drop the
    domain-specific goal high-predicate guard — the simulator never marks a
    high state as a goal, and including such a guard leaves the relaxed
    graph with ``0 operators`` and PRP bails out with "No solution".
    """
    return "(and (not (vStart)) )"


def patch_domain_pddl(path: str, domain_key: str) -> bool:
    """Inject the synthetic `goal` action into the autogenerated domain PDDL.

    Returns True if the file was modified, False otherwise.
    """
    if not os.path.isfile(path):
        print(f"  skip (missing): {path}")
        return False
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()

    if "patched_goal_act" in text:
        print(f"  already patched: {path}")
        return False

    pre = patched_precondition(domain_key)
    goal_action = (
        "\n    (:action patched_goal_act\n"
        "    :parameters ()\n"
        f"        :precondition {pre}\n"
        "        :effect (and (vGoal) (not (vStart)) )\n"
        "    )"
    )
    # Inject just before the closing ')' of the domain.
    new_text = re.sub(r"\n\)\s*\Z", goal_action + "\n)\n", text, count=1)
    if new_text == text:
        print(f"  WARN: could not locate closing ')' in {path}")
        return False
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new_text)
    print(f"  patched: {path}")
    return True


def main(argv: List[str]) -> int:
    if not argv:
        print("usage: patch_fond_goal.py <autogenerated_dir>", file=sys.stderr)
        return 2
    target = argv[0]
    if not os.path.isdir(target):
        print(f"not a directory: {target}", file=sys.stderr)
        return 2

    modified = 0
    for key in DOMAIN_GOAL_PREDICATES:
        d_path = os.path.join(target, f"fond_{key}_d.pddl")
        if patch_domain_pddl(d_path, key):
            modified += 1
    print(f"\nPatched {modified} domain file(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))