(define (domain deliveryfuel)
    (:requirements :strips :typing :equality :derived-predicates :negative-preconditions :universal-preconditions)
    (:types PackageType)
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (:predicates
        (atDepot)
        (atCustomer)
        (atDepotPkg ?p - PackageType)
        (inTruck ?p - PackageType)
        (delivered ?p - PackageType)
        (fuelOK)
        (fuelLow)
        (vStart)
        (Vgoal)
        (allDelivered)
        (h_carrying)
    )
    (:derived (allDelivered)
        (forall (?p - PackageType) (delivered ?p))
    )
    (:derived (h_carrying)
        (exists (?p - PackageType) (inTruck ?p))
    )
    ;; ##### ACTIONS #####
    (:action loadPkg
        :parameters (?p - PackageType)
        :precondition (and (atDepot) (atDepotPkg ?p) (fuelOK))
        :effect (and (inTruck ?p) (not (atDepotPkg ?p)))
    )
    (:action unloadPkg
        :parameters (?p - PackageType)
        :precondition (and (atCustomer) (inTruck ?p))
        :effect (and (delivered ?p) (not (inTruck ?p)))
    )
    (:action moveToCustomer
        :parameters ()
        :precondition (and (atDepot) (fuelOK))
        :effect (and (atCustomer) (not (atDepot)) (not (fuelOK)) (fuelLow))
    )
    (:action moveToDepot
        :parameters ()
        :precondition (and (atCustomer) (fuelOK))
        :effect (and (atDepot) (not (atCustomer)) (not (fuelOK)) (fuelLow))
    )
    (:action refuel
        :parameters ()
        :precondition (and (atDepot) (fuelLow))
        :effect (and (fuelOK) (not (fuelLow)))
    )
    (:formula_for_initial_states (and (atDepot) (fuelOK) (not (fuelLow)) (exists (?p - PackageType) (atDepotPkg ?p))))
    (:formula_for_goals (and (atDepot) (allDelivered)))
)
