(define (problem deliveryfuel_p2)
    (:domain deliveryfuel)
    (:objects p1 p2 - PackageType)
    (:init
        (atDepot)
        (fuelOK)
        (not (fuelLow))
        (atDepotPkg p1)
        (atDepotPkg p2)
        (not (inTruck p1))
        (not (inTruck p2))
        (not (delivered p1))
        (not (delivered p2))
    )
    (:goal (and (atDepot) (delivered p1) (delivered p2)))
)
