(define (problem deliveryfuel_p3)
    (:domain deliveryfuel)
    (:objects p1 p2 p3 - PackageType)
    (:init
        (atDepot)
        (fuelOK)
        (not (fuelLow))
        (atDepotPkg p1)
        (atDepotPkg p2)
        (atDepotPkg p3)
        (not (inTruck p1))
        (not (inTruck p2))
        (not (inTruck p3))
        (not (delivered p1))
        (not (delivered p2))
        (not (delivered p3))
    )
    (:goal (and (atDepot) (delivered p1) (delivered p2) (delivered p3)))
)
